name: expense
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  intl: ^0.18.0
  sqflite: ^2.2.8+2
  month_year_picker: ^0.3.0+1
  flutter_speed_dial: ^6.2.0
  events_emitter: ^0.5.2
  dynamic_color: ^1.6.5
  google_fonts: ^4.0.4
  sqflite_common_ffi: ^2.2.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  currency_picker: ^2.0.16
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
